### ISSUE TITLE
Please block tracker from ga.giuem.com

### ISSUE THREAD

**Issue by kkren** [Crystal-RainSlide/AdditionalFiltersCN#1]
ga.giuem.com is a domain that hold google analysis proxy service, so users in china mainland can be tracked by google analysis. However, many users are not aware of being tracked by this. 
[This](https://www.giuem.com/google-analytics-loading-optimize/) explained how this proxy works.
[This](https://blog.nfz.moe/) is an example site using this tracker

**Comment by Crystal-RainSlide** [comment]
Got it
