### ISSUE TITLE
你好

### ISSUE THREAD

**Issue by ghost** [Crystal-RainSlide/AdditionalFiltersCN#2]
请问现在还有继续添加新的规则吗?

这几个可以请你封锁吗?
https://support.google.com/analytics/answer/1011829?hl=zh-Hans
||ad.ettoday.net
||imp.appledaily.com
||edgecast-vod.yahoo.net
||edgecast-vod.yimg.com

**Comment by Crystal-RainSlide** [comment]
为什么立刻关闭了 issue，为什么删号？
